/* ROUGE visual editor — Supabase Auth + site_content */
(function(){
  const params=new URLSearchParams(location.search); if(params.get('edit')!=='1')return;
  const AUTH_CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
  let supa=null, session=null;
  function pageKeyFromPath(){const file=(location.pathname.split('/').pop()||'index.html').replace('.html','');return file||'index';}
  function toast(msg,isError){let t=document.getElementById('rougeEditToast');if(!t){t=document.createElement('div');t.id='rougeEditToast';Object.assign(t.style,{position:'fixed',left:'50%',bottom:'90px',transform:'translateX(-50%)',background:'#1a1a1a',color:'#fff',padding:'10px 18px',borderRadius:'4px',font:'500 12px/1.4 Manrope,sans-serif',letterSpacing:'.04em',zIndex:999999,boxShadow:'0 8px 24px rgba(0,0,0,.4)',transition:'opacity .25s',opacity:'0'});document.body.appendChild(t)}t.style.background=isError?'#7a1a1a':'#1a1a1a';t.textContent=msg;t.style.opacity='1';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.opacity='0',2200)}
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  async function ensureAuth(){
    if(!window.supabase) await loadScript(AUTH_CDN);
    supa=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
    const current=(await supa.auth.getSession()).data.session;
    if(current){session=current;return true;}
    const email=prompt('ROUGE editor email'); if(!email)return false;
    const password=prompt('ROUGE editor password'); if(!password)return false;
    const result=await supa.auth.signInWithPassword({email:email.trim(),password});
    if(result.error){toast(result.error.message,true);return false;}
    session=result.data.session; return !!session;
  }
  async function isAdmin(){if(!session)return false;const rows=await sbFetchWithToken('/admin_users?select=user_id&user_id=eq.'+encodeURIComponent(session.user.id),session.access_token);return Array.isArray(rows)&&rows.length>0;}
  async function saveKey(key,type,value){
    if(!session||!(await isAdmin())){toast('Admin access is required.',true);return false;}
    try{await sbFetchWithToken('/site_content?on_conflict=key',session.access_token,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key,type,value,page:pageKeyFromPath(),status:'Active',updated_at:new Date().toISOString()})});ROUGE_CONTENT[key]={value,type};toast('Saved ✓');return true;}catch(e){toast('Not saved — '+e.message,true);return false;}
  }
  function injectStyles(){const s=document.createElement('style');s.textContent=`[data-ck]{outline:1px dashed transparent;outline-offset:3px;cursor:pointer;transition:outline-color .15s}[data-ck]:hover{outline-color:#ff3b3b}.rouge-edit-badge{position:fixed;left:20px;bottom:20px;z-index:999999;background:#c02032;color:#fff;font:600 11px/1 Manrope,sans-serif;letter-spacing:.12em;padding:10px 16px;border-radius:3px;box-shadow:0 8px 24px rgba(0,0,0,.35)}.rouge-edit-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:999998}.rouge-edit-panel{position:fixed;z-index:999999;top:50%;left:50%;transform:translate(-50%,-50%);background:#fff;color:#1a1a1a;border-radius:6px;box-shadow:0 12px 40px rgba(0,0,0,.35);padding:18px;width:min(420px,90vw);max-height:80vh;overflow-y:auto;font:400 13px/1.5 Manrope,sans-serif}.rouge-edit-panel textarea,.rouge-edit-panel input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #ddd;border-radius:4px;font:inherit;margin-top:8px;resize:vertical}.rouge-edit-panel .rouge-edit-row{display:flex;gap:8px;margin-top:14px;position:sticky;bottom:0;background:#fff;padding-top:6px}.rouge-edit-panel button{flex:1;padding:10px;border:none;border-radius:4px;font:600 11px/1 Manrope,sans-serif;letter-spacing:.06em;cursor:pointer}.rouge-edit-save{background:#c02032;color:#fff}.rouge-edit-cancel{background:#eee;color:#333}.rouge-edit-preview{width:100%;max-height:220px;object-fit:cover;border-radius:4px;margin-top:8px;background:#f2f2f2}.rouge-edit-label{font:600 10px/1 Manrope,sans-serif;letter-spacing:.1em;color:#888;text-transform:uppercase}`;document.head.appendChild(s)}
  function closePanel(){document.getElementById('rougeEditPanel')?.remove();document.getElementById('rougeEditBackdrop')?.remove()}
  function openBackdrop(){const b=document.createElement('div');b.id='rougeEditBackdrop';b.className='rouge-edit-backdrop';b.onclick=closePanel;document.body.appendChild(b)}
  function openTextPanel(el,key){closePanel();openBackdrop();const panel=document.createElement('div');panel.id='rougeEditPanel';panel.className='rouge-edit-panel';const current=(ROUGE_CONTENT[key]&&ROUGE_CONTENT[key].value)||el.textContent.trim();panel.innerHTML=`<div class="rouge-edit-label">EDITING: ${escapeHtml(key)}</div><textarea rows="6">${escapeHtml(current)}</textarea><div class="rouge-edit-row"><button class="rouge-edit-save">SAVE</button><button class="rouge-edit-cancel">CANCEL</button></div>`;document.body.appendChild(panel);const textarea=panel.querySelector('textarea');textarea.focus();panel.querySelector('.rouge-edit-cancel').onclick=closePanel;panel.querySelector('.rouge-edit-save').onclick=async()=>{const ok=await saveKey(key,'text',textarea.value.trim());if(ok){el.textContent=textarea.value.trim();closePanel()}}}
  function openImagePanel(el,key){closePanel();openBackdrop();const panel=document.createElement('div');panel.id='rougeEditPanel';panel.className='rouge-edit-panel';const current=(ROUGE_CONTENT[key]&&ROUGE_CONTENT[key].value)||'';panel.innerHTML=`<div class="rouge-edit-label">EDITING IMAGE: ${escapeHtml(key)}</div><input type="text" placeholder="Image URL" value="${escapeHtml(current)}"><img class="rouge-edit-preview" src="${normalizeImageUrl(current)}"><div class="rouge-edit-row"><button class="rouge-edit-save">SAVE</button><button class="rouge-edit-cancel">CANCEL</button></div>`;document.body.appendChild(panel);const input=panel.querySelector('input'),preview=panel.querySelector('.rouge-edit-preview');input.focus();input.addEventListener('input',()=>preview.src=normalizeImageUrl(input.value.trim()));panel.querySelector('.rouge-edit-cancel').onclick=closePanel;panel.querySelector('.rouge-edit-save').onclick=async()=>{const url=input.value.trim();const ok=await saveKey(key,'image',url);if(ok){if(el.tagName==='IMG')el.src=normalizeImageUrl(url);else el.style.backgroundImage=`url("${normalizeImageUrl(url).replace(/"/g,'\\"')}")`;closePanel()}}}
  function isImageTarget(el){const t=(el.getAttribute('data-ck-type')||'').toLowerCase();if(t)return t==='image';return el.tagName==='IMG'||getComputedStyle(el).backgroundImage!=='none'}
  async function start(){injectStyles();const badge=document.createElement('div');badge.className='rouge-edit-badge';badge.textContent='ROUGE EDIT MODE — click any dashed block';document.body.appendChild(badge);document.addEventListener('click',e=>{const el=e.target.closest('[data-ck]');if(!el)return;e.preventDefault();e.stopPropagation();const key=el.getAttribute('data-ck');if(isImageTarget(el))openImagePanel(el,key);else openTextPanel(el,key)},true);document.addEventListener('click',e=>{if(e.target.id==='rougeEditBackdrop')return;if(!e.target.closest('.rouge-edit-panel')&&!e.target.closest('[data-ck]'))closePanel()})}
  (async()=>{try{const ok=await ensureAuth();if(!ok)return;const admin=await isAdmin();if(!admin){toast('Your account is not an ROUGE admin.',true);return;}start()}catch(e){console.error(e);toast('Editor login failed.',true)}})();
})();
